function u16(b, o) { return b[o] | (b[o + 1] << 8); }
function u32(b, o) { return (b[o] | (b[o + 1] << 8) | (b[o + 2] << 16) | (b[o + 3] << 24)) >>> 0; }
function text(b, o, n) { return String.fromCharCode(...b.slice(o, o + n)); }
function parse(bytes) {
  if (text(bytes, 0, 3) === 'GIF') return {format:'GIF', fields:[['0x00–05','Signature',text(bytes,0,6),'The file announces GIF87a or GIF89a.'],['0x06–07','Canvas width',u16(bytes,6)+' px','Little-endian 16-bit number.'],['0x08–09','Canvas height',u16(bytes,8)+' px','Little-endian 16-bit number.'],['0x0A','Packed fields','0x'+bytes[10].toString(16).padStart(2,'0'),'Flags for the global palette.']]};
  if (text(bytes, 0, 2) === 'BM') return {format:'BMP', fields:[['0x00–01','Signature','BM','Windows bitmap marker.'],['0x02–05','File size',u32(bytes,2)+' bytes','Little-endian 32-bit number.'],['0x0A–0D','Pixel data offset','0x'+u32(bytes,10).toString(16),'Where the image pixels begin.'],['0x12–15','Width',u32(bytes,18)+' px','Stored in the DIB header.'],['0x16–19','Height',u32(bytes,22)+' px','Stored in the DIB header.']]};
  if (text(bytes, 0, 4) === 'RIFF' && text(bytes, 8, 4) === 'WAVE') return {format:'WAV', fields:[['0x00–03','Container','RIFF','Resource Interchange File Format.'],['0x04–07','Container size',u32(bytes,4)+' bytes','Bytes after this field.'],['0x08–0B','Form type','WAVE','This RIFF file holds audio.'],['0x14–15','Audio format',u16(bytes,20) === 1 ? 'PCM' : u16(bytes,20),'1 means uncompressed PCM.'],['0x16–17','Channels',u16(bytes,22),'One is mono; two is stereo.'],['0x18–1B','Sample rate',u32(bytes,24)+' Hz','Samples captured each second.']]};
  throw new Error('This instrument recognizes GIF, BMP, and WAV specimens.');
}
if (typeof module !== 'undefined') module.exports = {parse};
if (typeof document !== 'undefined') { const file=document.querySelector('#file'), bytes=document.querySelector('#bytes'), parsed=document.querySelector('#parsed'), status=document.querySelector('#status'); function show(name,data){try{const b=new Uint8Array(data);const r=parse(b);status.textContent=`${name}: ${r.format} recognized (${b.length} bytes).`;bytes.textContent=Array.from(b).map((x,i)=>`${i.toString(16).padStart(4,'0')}: ${x.toString(16).padStart(2,'0')}`).join('\n');parsed.innerHTML=`<h3>${r.format}</h3>`+r.fields.map(f=>`<div class="field"><span class="offset">${f[0]}</span><span><b>${f[1]}:</b> ${f[2]}<br><small>${f[3]}</small></span></div>`).join('')}catch(e){status.textContent=e.message;bytes.textContent='—';parsed.textContent='No parsed structure.'}} file.addEventListener('change',async e=>{const f=e.target.files[0];if(f)show(f.name,await f.arrayBuffer())});document.querySelectorAll('[data-fixture]').forEach(b=>b.addEventListener('click',async()=>show(b.dataset.fixture,await (await fetch('fixtures/'+b.dataset.fixture)).arrayBuffer()))); }
